const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

console.log('Linking CLI...');

const WT_LOCAL_MARKER = 'generated by @tokenbooks/wt local build';

function quoteForSh(value) {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function pathIncludes(dir) {
  const entries = (process.env.PATH ?? '').split(path.delimiter);
  return entries.some((entry) => path.resolve(entry) === path.resolve(dir));
}

function canOverwriteShim(shimPath) {
  if (!fs.existsSync(shimPath)) {
    return true;
  }

  const stat = fs.lstatSync(shimPath);
  if (stat.isSymbolicLink()) {
    return true;
  }
  if (!stat.isFile()) {
    return false;
  }

  const content = fs.readFileSync(shimPath, 'utf8');
  return content.includes(WT_LOCAL_MARKER);
}

function writeShim(shimPath, cliPath) {
  if (!canOverwriteShim(shimPath)) {
    console.warn(`Skipping wt-local shim; existing file is not managed by this build: ${shimPath}`);
    return false;
  }

  fs.mkdirSync(path.dirname(shimPath), { recursive: true });
  if (fs.existsSync(shimPath)) {
    fs.rmSync(shimPath, { force: true });
  }

  const content = [
    '#!/bin/sh',
    `# ${WT_LOCAL_MARKER}`,
    `exec ${quoteForSh(cliPath)} "$@"`,
    '',
  ].join('\n');

  fs.writeFileSync(shimPath, content, 'utf8');
  fs.chmodSync(shimPath, '755');
  console.log('wt-local shim prepared at', shimPath);
  return true;
}

try {
  const cliPath = path.join(__dirname, '..', 'dist', 'cli.js');

  if (!fs.existsSync(cliPath)) {
    throw new Error(
      `CLI file not found at ${cliPath}. Make sure to run 'tsc' first.`,
    );
  }

  // Make executable
  fs.chmodSync(cliPath, '755');

  // Add shebang if not present
  let content = fs.readFileSync(cliPath, 'utf8');
  if (!content.startsWith('#!/usr/bin/env node')) {
    content = '#!/usr/bin/env node\n' + content;
    fs.writeFileSync(cliPath, content);
  }

  console.log('CLI prepared at', cliPath);

  writeShim(path.join(__dirname, '..', 'node_modules', '.bin', 'wt-local'), cliPath);

  const globalBinDir = process.env.WT_LOCAL_BIN_DIR
    || process.env.PNPM_HOME
    || path.join(os.homedir(), 'Library', 'pnpm');
  if (writeShim(path.join(globalBinDir, 'wt-local'), cliPath) && !pathIncludes(globalBinDir)) {
    console.warn(`wt-local was linked into ${globalBinDir}, but that directory is not on PATH.`);
  }
} catch (error) {
  console.error('CLI linking failed:', error.message);
  process.exit(1);
}
